---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zenghuian.
--- DateTime: 2019-08-12 18:05
---

local View = {}

function View:Start()
    print("start scripts")
    local loginBtn = self.LoginBtn
    ChangeUIText(self.LoginText,"登录")
    RegistButtonEvent(loginBtn,self.Call)
end

function View:Call()


    print("Call")
end

return View
