---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by llll.
--- DateTime: 2019/8/28 23:28
---


local fmt = require("fmt.fmt")

local View = {}

print("start scripts")

function View:Start()
    print("start scripts")
    print(self)
end

return View
