---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zenghuian.
--- DateTime: 2019-08-12 18:05
---

local view = {}

print("start scripts")

function view:awake()
    print("start scripts")
end

return view

